name: Products Service CI/CD

on:
  push:
    branches:
      - "feature/*"   # déclenche sur toutes les branches feature
  pull_request:
    branches:
      - main          # déclenche les tests/audits sur PR vers main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd products-service
          npm install

      - name: Run tests
        run: |
          cd products-service
          npm test

      - name: Audit dependencies
        run: |
          cd products-service
          npm audit --audit-level=high

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify DockerHub login
        run: docker info

      - name: Build & Push Products Service Image
        uses: docker/build-push-action@v4
        with:
          context: ./products-service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/products-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/products-service:${{ github.ref_name }}