name: Products Service CI

on:
  push:
    branches:
      - feature/products-service
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd products-service
          npm install

      - name: Run tests
        run: |
          cd products-service
          npm test

      - name: Audit dependencies
        run: |
          cd products-service
          npm audit --audit-level=high

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Products Service Image
        run: |
          cd products-service
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/products-service:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/products-service:latest